// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/agent_loop_api.dart';
import 'api/chat_protocol_api.dart';
import 'api/mcp_api.dart';
import 'api/mcp_client_api.dart';
import 'api/modal_provider_api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiModalProviderApiInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -1476575372;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'jasmine_agent',
        ioDirectory: 'rust-lib/jasmine-agent/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateApiMcpApiBuildCallToolRequest({
    required String idJson,
    required String toolName,
    String? argsJson,
  });

  Future<String> crateApiMcpApiBuildGetPromptRequest({
    required String idJson,
    required String promptName,
    String? argsJson,
  });

  Future<String> crateApiMcpApiBuildHealthCheckRequest({
    required String idJson,
  });

  Future<String> crateApiMcpApiBuildInitializeRequest({
    required String clientName,
    required String clientVersion,
    String? protocolVersion,
  });

  Future<String> crateApiMcpApiBuildJsonRpcNotification({
    required String method,
    String? paramsJson,
  });

  Future<String> crateApiMcpApiBuildJsonRpcRequest({
    required String idJson,
    required String method,
    String? paramsJson,
  });

  Future<String> crateApiMcpApiBuildListPromptsRequest({
    required String idJson,
  });

  Future<String> crateApiMcpApiBuildListResourcesRequest({
    required String idJson,
  });

  Future<String> crateApiMcpApiBuildListToolsRequest({required String idJson});

  Future<String> crateApiMcpApiBuildReadResourceRequest({
    required String idJson,
    required String uri,
  });

  String crateApiChatProtocolApiChatAggregateToolCall({
    required int index,
    String? id,
    String? name,
    String? argsFragment,
    String? aggregatorJson,
  });

  String crateApiChatProtocolApiChatBuildClaudeBody({
    required String modelId,
    required String messagesJson,
    String? systemPrompt,
    String? toolsJson,
    required bool stream,
    double? temperature,
    double? topP,
    int? maxTokens,
    int? thinkingBudget,
    required bool isReasoning,
    String? extraBodyJson,
  });

  String crateApiChatProtocolApiChatBuildClaudeUrl({required String baseUrl});

  String crateApiChatProtocolApiChatBuildImagesBody({
    required String modelId,
    required String prompt,
    int? n,
    String? size,
    String? quality,
  });

  String crateApiChatProtocolApiChatBuildOpenaiChatBody({
    required String modelId,
    required String messagesJson,
    String? toolsJson,
    required bool stream,
    double? temperature,
    double? topP,
    int? maxTokens,
    int? thinkingBudget,
    required bool isReasoning,
    String? extraBodyJson,
  });

  String crateApiChatProtocolApiChatBuildOpenaiResponsesBody({
    required String modelId,
    required String inputJson,
    String? instructions,
    String? toolsJson,
    required bool stream,
    double? temperature,
    double? topP,
    int? maxTokens,
    int? thinkingBudget,
    required bool isReasoning,
  });

  String crateApiChatProtocolApiChatBuildOpenaiUrl({
    required String baseUrl,
    String? chatPath,
    required bool useResponseApi,
  });

  String crateApiChatProtocolApiChatClassifyVendor({
    required String providerId,
    required String baseUrl,
    required String modelId,
  });

  String crateApiChatProtocolApiChatCleanToolSchema({required String toolJson});

  String crateApiChatProtocolApiChatCompletionTokensKey({
    required String vendorStr,
  });

  String crateApiChatProtocolApiChatCopyMessage({required String msgJson});

  String crateApiChatProtocolApiChatFinalizeToolCalls({
    required String aggregatorJson,
  });

  bool crateApiChatProtocolApiChatIsBuiltinSearchSupported({
    required String modelId,
    required String providerType,
  });

  bool crateApiChatProtocolApiChatIsKimiThinkingModel({
    required String modelId,
  });

  bool crateApiChatProtocolApiChatIsSseDone({required String line});

  bool crateApiChatProtocolApiChatNeedsReasoningEcho({
    required String vendorStr,
  });

  String crateApiChatProtocolApiChatNormalizeReasoningEffort({
    required String effort,
    required String modelId,
  });

  String crateApiChatProtocolApiChatParseClaudeEvent({required String jsonStr});

  String crateApiChatProtocolApiChatParseOpenaiChunk({required String jsonStr});

  String? crateApiChatProtocolApiChatParseSseLine({required String line});

  String crateApiChatProtocolApiChatParseTextAndImages({required String raw});

  String crateApiChatProtocolApiChatSanitizeGpt5Body({
    required String bodyJson,
    required String modelId,
    required String effort,
  });

  String crateApiChatProtocolApiChatSanitizeUnicode({required String text});

  String crateApiChatProtocolApiChatToClaudeToolsFormat({
    required String toolsJson,
  });

  Future<String> crateApiMcpApiCreateDefaultMcpConfig({
    required String name,
    required String transport,
    required String url,
  });

  String crateApiMcpApiDefaultMcpVersion();

  String crateApiMcpApiExportMcpServersUiJson({
    required String serversJson,
    required bool isDesktop,
  });

  String crateApiMcpApiGetMcpMethodNames();

  Future<void> crateApiModalProviderApiInitApp();

  bool crateApiMcpApiIsMcpVersionSupported({required String version});

  String crateApiMcpApiJsonRpcErrorDetails({required int code});

  String crateApiMcpApiLogLevelName({required String level});

  String crateApiMcpClientApiMcpBuildTransportConfig({
    required String url,
    String? headersJson,
    required String transport,
    required BigInt timeoutMs,
  });

  String crateApiMcpClientApiMcpCallTool({
    required String url,
    String? headersJson,
    required String transport,
    required String toolName,
    String? argsJson,
    required BigInt timeoutMs,
  });

  String crateApiMcpClientApiMcpConnect({
    required String url,
    String? headersJson,
    required String transport,
    required BigInt timeoutMs,
  });

  String crateApiMcpClientApiMcpListPrompts({
    required String url,
    String? headersJson,
    required String transport,
    required BigInt timeoutMs,
  });

  String crateApiMcpClientApiMcpListResources({
    required String url,
    String? headersJson,
    required String transport,
    required BigInt timeoutMs,
  });

  String crateApiMcpClientApiMcpListTools({
    required String url,
    String? headersJson,
    required String transport,
    required BigInt timeoutMs,
  });

  Future<String> crateApiModalProviderApiModalProviderClassifyProviderKind({
    required String providerId,
    String? explicitType,
  });

  Future<String> crateApiModalProviderApiModalProviderCreateDefaultConfig({
    required String providerId,
    String? displayName,
  });

  Future<String> crateApiModalProviderApiModalProviderDefaultBaseUrl({
    required String providerId,
  });

  Future<String>
  crateApiModalProviderApiModalProviderGetProviderDefaultHeaders({
    required String configJson,
  });

  Future<String> crateApiModalProviderApiModalProviderListModels({
    required String configJson,
    String? siliconflowFallbackKey,
  });

  Future<String> crateApiModalProviderApiModalProviderResolveApiModelId({
    required String configJson,
    required String modelId,
  });

  Future<void> crateApiModalProviderApiModalProviderTestConnection({
    required String configJson,
    required String modelId,
    required bool useStream,
    String? siliconflowFallbackKey,
  });

  Future<void> crateApiModalProviderApiModalProviderValidateProviderConfig({
    required String configJson,
  });

  String? crateApiMcpApiNegotiateMcpVersion({
    required List<String> clientVersions,
    required List<String> serverVersions,
  });

  String crateApiMcpApiNormalizeToolArguments({
    String? schemaJson,
    required String argsJson,
  });

  String crateApiMcpApiParseMcpImportJson({
    required String rawJson,
    required bool isDesktop,
  });

  String crateApiAgentLoopApiRunClaudeAgentLoop({
    required String baseUrl,
    required String apiKey,
    required String modelId,
    required String messagesJson,
    String? systemPrompt,
    String? toolsJson,
    required bool stream,
    required bool isReasoning,
    int? thinkingBudget,
    double? temperature,
    int? maxTokens,
  });

  String crateApiAgentLoopApiRunOpenaiAgentLoop({
    required String baseUrl,
    required String apiKey,
    required String modelId,
    required String messagesJson,
    String? toolsJson,
    required bool stream,
    required bool isReasoning,
    int? thinkingBudget,
    double? temperature,
    int? maxTokens,
    required bool useResponseApi,
  });

  Future<String> crateApiMcpApiSummarizeServerTools({
    required String toolsJson,
  });

  List<String> crateApiMcpApiSupportedMcpVersions();

  Future<void> crateApiMcpApiValidateMcpServerConfig({
    required String configJson,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiMcpApiBuildCallToolRequest({
    required String idJson,
    required String toolName,
    String? argsJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(idJson, serializer);
          sse_encode_String(toolName, serializer);
          sse_encode_opt_String(argsJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMcpApiBuildCallToolRequestConstMeta,
        argValues: [idJson, toolName, argsJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMcpApiBuildCallToolRequestConstMeta =>
      const TaskConstMeta(
        debugName: "build_call_tool_request",
        argNames: ["idJson", "toolName", "argsJson"],
      );

  @override
  Future<String> crateApiMcpApiBuildGetPromptRequest({
    required String idJson,
    required String promptName,
    String? argsJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(idJson, serializer);
          sse_encode_String(promptName, serializer);
          sse_encode_opt_String(argsJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMcpApiBuildGetPromptRequestConstMeta,
        argValues: [idJson, promptName, argsJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMcpApiBuildGetPromptRequestConstMeta =>
      const TaskConstMeta(
        debugName: "build_get_prompt_request",
        argNames: ["idJson", "promptName", "argsJson"],
      );

  @override
  Future<String> crateApiMcpApiBuildHealthCheckRequest({
    required String idJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(idJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMcpApiBuildHealthCheckRequestConstMeta,
        argValues: [idJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMcpApiBuildHealthCheckRequestConstMeta =>
      const TaskConstMeta(
        debugName: "build_health_check_request",
        argNames: ["idJson"],
      );

  @override
  Future<String> crateApiMcpApiBuildInitializeRequest({
    required String clientName,
    required String clientVersion,
    String? protocolVersion,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(clientName, serializer);
          sse_encode_String(clientVersion, serializer);
          sse_encode_opt_String(protocolVersion, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMcpApiBuildInitializeRequestConstMeta,
        argValues: [clientName, clientVersion, protocolVersion],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMcpApiBuildInitializeRequestConstMeta =>
      const TaskConstMeta(
        debugName: "build_initialize_request",
        argNames: ["clientName", "clientVersion", "protocolVersion"],
      );

  @override
  Future<String> crateApiMcpApiBuildJsonRpcNotification({
    required String method,
    String? paramsJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(method, serializer);
          sse_encode_opt_String(paramsJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMcpApiBuildJsonRpcNotificationConstMeta,
        argValues: [method, paramsJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMcpApiBuildJsonRpcNotificationConstMeta =>
      const TaskConstMeta(
        debugName: "build_json_rpc_notification",
        argNames: ["method", "paramsJson"],
      );

  @override
  Future<String> crateApiMcpApiBuildJsonRpcRequest({
    required String idJson,
    required String method,
    String? paramsJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(idJson, serializer);
          sse_encode_String(method, serializer);
          sse_encode_opt_String(paramsJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMcpApiBuildJsonRpcRequestConstMeta,
        argValues: [idJson, method, paramsJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMcpApiBuildJsonRpcRequestConstMeta =>
      const TaskConstMeta(
        debugName: "build_json_rpc_request",
        argNames: ["idJson", "method", "paramsJson"],
      );

  @override
  Future<String> crateApiMcpApiBuildListPromptsRequest({
    required String idJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(idJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMcpApiBuildListPromptsRequestConstMeta,
        argValues: [idJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMcpApiBuildListPromptsRequestConstMeta =>
      const TaskConstMeta(
        debugName: "build_list_prompts_request",
        argNames: ["idJson"],
      );

  @override
  Future<String> crateApiMcpApiBuildListResourcesRequest({
    required String idJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(idJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMcpApiBuildListResourcesRequestConstMeta,
        argValues: [idJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMcpApiBuildListResourcesRequestConstMeta =>
      const TaskConstMeta(
        debugName: "build_list_resources_request",
        argNames: ["idJson"],
      );

  @override
  Future<String> crateApiMcpApiBuildListToolsRequest({required String idJson}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(idJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMcpApiBuildListToolsRequestConstMeta,
        argValues: [idJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMcpApiBuildListToolsRequestConstMeta =>
      const TaskConstMeta(
        debugName: "build_list_tools_request",
        argNames: ["idJson"],
      );

  @override
  Future<String> crateApiMcpApiBuildReadResourceRequest({
    required String idJson,
    required String uri,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(idJson, serializer);
          sse_encode_String(uri, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMcpApiBuildReadResourceRequestConstMeta,
        argValues: [idJson, uri],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMcpApiBuildReadResourceRequestConstMeta =>
      const TaskConstMeta(
        debugName: "build_read_resource_request",
        argNames: ["idJson", "uri"],
      );

  @override
  String crateApiChatProtocolApiChatAggregateToolCall({
    required int index,
    String? id,
    String? name,
    String? argsFragment,
    String? aggregatorJson,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_32(index, serializer);
          sse_encode_opt_String(id, serializer);
          sse_encode_opt_String(name, serializer);
          sse_encode_opt_String(argsFragment, serializer);
          sse_encode_opt_String(aggregatorJson, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiChatProtocolApiChatAggregateToolCallConstMeta,
        argValues: [index, id, name, argsFragment, aggregatorJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatProtocolApiChatAggregateToolCallConstMeta =>
      const TaskConstMeta(
        debugName: "chat_aggregate_tool_call",
        argNames: ["index", "id", "name", "argsFragment", "aggregatorJson"],
      );

  @override
  String crateApiChatProtocolApiChatBuildClaudeBody({
    required String modelId,
    required String messagesJson,
    String? systemPrompt,
    String? toolsJson,
    required bool stream,
    double? temperature,
    double? topP,
    int? maxTokens,
    int? thinkingBudget,
    required bool isReasoning,
    String? extraBodyJson,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(modelId, serializer);
          sse_encode_String(messagesJson, serializer);
          sse_encode_opt_String(systemPrompt, serializer);
          sse_encode_opt_String(toolsJson, serializer);
          sse_encode_bool(stream, serializer);
          sse_encode_opt_box_autoadd_f_64(temperature, serializer);
          sse_encode_opt_box_autoadd_f_64(topP, serializer);
          sse_encode_opt_box_autoadd_i_32(maxTokens, serializer);
          sse_encode_opt_box_autoadd_i_32(thinkingBudget, serializer);
          sse_encode_bool(isReasoning, serializer);
          sse_encode_opt_String(extraBodyJson, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiChatProtocolApiChatBuildClaudeBodyConstMeta,
        argValues: [
          modelId,
          messagesJson,
          systemPrompt,
          toolsJson,
          stream,
          temperature,
          topP,
          maxTokens,
          thinkingBudget,
          isReasoning,
          extraBodyJson,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatProtocolApiChatBuildClaudeBodyConstMeta =>
      const TaskConstMeta(
        debugName: "chat_build_claude_body",
        argNames: [
          "modelId",
          "messagesJson",
          "systemPrompt",
          "toolsJson",
          "stream",
          "temperature",
          "topP",
          "maxTokens",
          "thinkingBudget",
          "isReasoning",
          "extraBodyJson",
        ],
      );

  @override
  String crateApiChatProtocolApiChatBuildClaudeUrl({required String baseUrl}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(baseUrl, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiChatProtocolApiChatBuildClaudeUrlConstMeta,
        argValues: [baseUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatProtocolApiChatBuildClaudeUrlConstMeta =>
      const TaskConstMeta(
        debugName: "chat_build_claude_url",
        argNames: ["baseUrl"],
      );

  @override
  String crateApiChatProtocolApiChatBuildImagesBody({
    required String modelId,
    required String prompt,
    int? n,
    String? size,
    String? quality,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(modelId, serializer);
          sse_encode_String(prompt, serializer);
          sse_encode_opt_box_autoadd_i_32(n, serializer);
          sse_encode_opt_String(size, serializer);
          sse_encode_opt_String(quality, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiChatProtocolApiChatBuildImagesBodyConstMeta,
        argValues: [modelId, prompt, n, size, quality],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatProtocolApiChatBuildImagesBodyConstMeta =>
      const TaskConstMeta(
        debugName: "chat_build_images_body",
        argNames: ["modelId", "prompt", "n", "size", "quality"],
      );

  @override
  String crateApiChatProtocolApiChatBuildOpenaiChatBody({
    required String modelId,
    required String messagesJson,
    String? toolsJson,
    required bool stream,
    double? temperature,
    double? topP,
    int? maxTokens,
    int? thinkingBudget,
    required bool isReasoning,
    String? extraBodyJson,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(modelId, serializer);
          sse_encode_String(messagesJson, serializer);
          sse_encode_opt_String(toolsJson, serializer);
          sse_encode_bool(stream, serializer);
          sse_encode_opt_box_autoadd_f_64(temperature, serializer);
          sse_encode_opt_box_autoadd_f_64(topP, serializer);
          sse_encode_opt_box_autoadd_i_32(maxTokens, serializer);
          sse_encode_opt_box_autoadd_i_32(thinkingBudget, serializer);
          sse_encode_bool(isReasoning, serializer);
          sse_encode_opt_String(extraBodyJson, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiChatProtocolApiChatBuildOpenaiChatBodyConstMeta,
        argValues: [
          modelId,
          messagesJson,
          toolsJson,
          stream,
          temperature,
          topP,
          maxTokens,
          thinkingBudget,
          isReasoning,
          extraBodyJson,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatProtocolApiChatBuildOpenaiChatBodyConstMeta =>
      const TaskConstMeta(
        debugName: "chat_build_openai_chat_body",
        argNames: [
          "modelId",
          "messagesJson",
          "toolsJson",
          "stream",
          "temperature",
          "topP",
          "maxTokens",
          "thinkingBudget",
          "isReasoning",
          "extraBodyJson",
        ],
      );

  @override
  String crateApiChatProtocolApiChatBuildOpenaiResponsesBody({
    required String modelId,
    required String inputJson,
    String? instructions,
    String? toolsJson,
    required bool stream,
    double? temperature,
    double? topP,
    int? maxTokens,
    int? thinkingBudget,
    required bool isReasoning,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(modelId, serializer);
          sse_encode_String(inputJson, serializer);
          sse_encode_opt_String(instructions, serializer);
          sse_encode_opt_String(toolsJson, serializer);
          sse_encode_bool(stream, serializer);
          sse_encode_opt_box_autoadd_f_64(temperature, serializer);
          sse_encode_opt_box_autoadd_f_64(topP, serializer);
          sse_encode_opt_box_autoadd_i_32(maxTokens, serializer);
          sse_encode_opt_box_autoadd_i_32(thinkingBudget, serializer);
          sse_encode_bool(isReasoning, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta:
            kCrateApiChatProtocolApiChatBuildOpenaiResponsesBodyConstMeta,
        argValues: [
          modelId,
          inputJson,
          instructions,
          toolsJson,
          stream,
          temperature,
          topP,
          maxTokens,
          thinkingBudget,
          isReasoning,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiChatProtocolApiChatBuildOpenaiResponsesBodyConstMeta =>
      const TaskConstMeta(
        debugName: "chat_build_openai_responses_body",
        argNames: [
          "modelId",
          "inputJson",
          "instructions",
          "toolsJson",
          "stream",
          "temperature",
          "topP",
          "maxTokens",
          "thinkingBudget",
          "isReasoning",
        ],
      );

  @override
  String crateApiChatProtocolApiChatBuildOpenaiUrl({
    required String baseUrl,
    String? chatPath,
    required bool useResponseApi,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(baseUrl, serializer);
          sse_encode_opt_String(chatPath, serializer);
          sse_encode_bool(useResponseApi, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiChatProtocolApiChatBuildOpenaiUrlConstMeta,
        argValues: [baseUrl, chatPath, useResponseApi],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatProtocolApiChatBuildOpenaiUrlConstMeta =>
      const TaskConstMeta(
        debugName: "chat_build_openai_url",
        argNames: ["baseUrl", "chatPath", "useResponseApi"],
      );

  @override
  String crateApiChatProtocolApiChatClassifyVendor({
    required String providerId,
    required String baseUrl,
    required String modelId,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(providerId, serializer);
          sse_encode_String(baseUrl, serializer);
          sse_encode_String(modelId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiChatProtocolApiChatClassifyVendorConstMeta,
        argValues: [providerId, baseUrl, modelId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatProtocolApiChatClassifyVendorConstMeta =>
      const TaskConstMeta(
        debugName: "chat_classify_vendor",
        argNames: ["providerId", "baseUrl", "modelId"],
      );

  @override
  String crateApiChatProtocolApiChatCleanToolSchema({
    required String toolJson,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(toolJson, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiChatProtocolApiChatCleanToolSchemaConstMeta,
        argValues: [toolJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatProtocolApiChatCleanToolSchemaConstMeta =>
      const TaskConstMeta(
        debugName: "chat_clean_tool_schema",
        argNames: ["toolJson"],
      );

  @override
  String crateApiChatProtocolApiChatCompletionTokensKey({
    required String vendorStr,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(vendorStr, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiChatProtocolApiChatCompletionTokensKeyConstMeta,
        argValues: [vendorStr],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatProtocolApiChatCompletionTokensKeyConstMeta =>
      const TaskConstMeta(
        debugName: "chat_completion_tokens_key",
        argNames: ["vendorStr"],
      );

  @override
  String crateApiChatProtocolApiChatCopyMessage({required String msgJson}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(msgJson, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiChatProtocolApiChatCopyMessageConstMeta,
        argValues: [msgJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatProtocolApiChatCopyMessageConstMeta =>
      const TaskConstMeta(
        debugName: "chat_copy_message",
        argNames: ["msgJson"],
      );

  @override
  String crateApiChatProtocolApiChatFinalizeToolCalls({
    required String aggregatorJson,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(aggregatorJson, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiChatProtocolApiChatFinalizeToolCallsConstMeta,
        argValues: [aggregatorJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatProtocolApiChatFinalizeToolCallsConstMeta =>
      const TaskConstMeta(
        debugName: "chat_finalize_tool_calls",
        argNames: ["aggregatorJson"],
      );

  @override
  bool crateApiChatProtocolApiChatIsBuiltinSearchSupported({
    required String modelId,
    required String providerType,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(modelId, serializer);
          sse_encode_String(providerType, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 23)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiChatProtocolApiChatIsBuiltinSearchSupportedConstMeta,
        argValues: [modelId, providerType],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiChatProtocolApiChatIsBuiltinSearchSupportedConstMeta =>
      const TaskConstMeta(
        debugName: "chat_is_builtin_search_supported",
        argNames: ["modelId", "providerType"],
      );

  @override
  bool crateApiChatProtocolApiChatIsKimiThinkingModel({
    required String modelId,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(modelId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 24)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiChatProtocolApiChatIsKimiThinkingModelConstMeta,
        argValues: [modelId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatProtocolApiChatIsKimiThinkingModelConstMeta =>
      const TaskConstMeta(
        debugName: "chat_is_kimi_thinking_model",
        argNames: ["modelId"],
      );

  @override
  bool crateApiChatProtocolApiChatIsSseDone({required String line}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(line, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 25)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiChatProtocolApiChatIsSseDoneConstMeta,
        argValues: [line],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatProtocolApiChatIsSseDoneConstMeta =>
      const TaskConstMeta(debugName: "chat_is_sse_done", argNames: ["line"]);

  @override
  bool crateApiChatProtocolApiChatNeedsReasoningEcho({
    required String vendorStr,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(vendorStr, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 26)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiChatProtocolApiChatNeedsReasoningEchoConstMeta,
        argValues: [vendorStr],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatProtocolApiChatNeedsReasoningEchoConstMeta =>
      const TaskConstMeta(
        debugName: "chat_needs_reasoning_echo",
        argNames: ["vendorStr"],
      );

  @override
  String crateApiChatProtocolApiChatNormalizeReasoningEffort({
    required String effort,
    required String modelId,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(effort, serializer);
          sse_encode_String(modelId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 27)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiChatProtocolApiChatNormalizeReasoningEffortConstMeta,
        argValues: [effort, modelId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiChatProtocolApiChatNormalizeReasoningEffortConstMeta =>
      const TaskConstMeta(
        debugName: "chat_normalize_reasoning_effort",
        argNames: ["effort", "modelId"],
      );

  @override
  String crateApiChatProtocolApiChatParseClaudeEvent({
    required String jsonStr,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(jsonStr, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 28)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiChatProtocolApiChatParseClaudeEventConstMeta,
        argValues: [jsonStr],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatProtocolApiChatParseClaudeEventConstMeta =>
      const TaskConstMeta(
        debugName: "chat_parse_claude_event",
        argNames: ["jsonStr"],
      );

  @override
  String crateApiChatProtocolApiChatParseOpenaiChunk({
    required String jsonStr,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(jsonStr, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 29)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiChatProtocolApiChatParseOpenaiChunkConstMeta,
        argValues: [jsonStr],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatProtocolApiChatParseOpenaiChunkConstMeta =>
      const TaskConstMeta(
        debugName: "chat_parse_openai_chunk",
        argNames: ["jsonStr"],
      );

  @override
  String? crateApiChatProtocolApiChatParseSseLine({required String line}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(line, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 30)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiChatProtocolApiChatParseSseLineConstMeta,
        argValues: [line],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatProtocolApiChatParseSseLineConstMeta =>
      const TaskConstMeta(debugName: "chat_parse_sse_line", argNames: ["line"]);

  @override
  String crateApiChatProtocolApiChatParseTextAndImages({required String raw}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(raw, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 31)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiChatProtocolApiChatParseTextAndImagesConstMeta,
        argValues: [raw],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatProtocolApiChatParseTextAndImagesConstMeta =>
      const TaskConstMeta(
        debugName: "chat_parse_text_and_images",
        argNames: ["raw"],
      );

  @override
  String crateApiChatProtocolApiChatSanitizeGpt5Body({
    required String bodyJson,
    required String modelId,
    required String effort,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(bodyJson, serializer);
          sse_encode_String(modelId, serializer);
          sse_encode_String(effort, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 32)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiChatProtocolApiChatSanitizeGpt5BodyConstMeta,
        argValues: [bodyJson, modelId, effort],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatProtocolApiChatSanitizeGpt5BodyConstMeta =>
      const TaskConstMeta(
        debugName: "chat_sanitize_gpt5_body",
        argNames: ["bodyJson", "modelId", "effort"],
      );

  @override
  String crateApiChatProtocolApiChatSanitizeUnicode({required String text}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(text, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 33)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiChatProtocolApiChatSanitizeUnicodeConstMeta,
        argValues: [text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatProtocolApiChatSanitizeUnicodeConstMeta =>
      const TaskConstMeta(
        debugName: "chat_sanitize_unicode",
        argNames: ["text"],
      );

  @override
  String crateApiChatProtocolApiChatToClaudeToolsFormat({
    required String toolsJson,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(toolsJson, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 34)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiChatProtocolApiChatToClaudeToolsFormatConstMeta,
        argValues: [toolsJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatProtocolApiChatToClaudeToolsFormatConstMeta =>
      const TaskConstMeta(
        debugName: "chat_to_claude_tools_format",
        argNames: ["toolsJson"],
      );

  @override
  Future<String> crateApiMcpApiCreateDefaultMcpConfig({
    required String name,
    required String transport,
    required String url,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          sse_encode_String(transport, serializer);
          sse_encode_String(url, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 35,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMcpApiCreateDefaultMcpConfigConstMeta,
        argValues: [name, transport, url],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMcpApiCreateDefaultMcpConfigConstMeta =>
      const TaskConstMeta(
        debugName: "create_default_mcp_config",
        argNames: ["name", "transport", "url"],
      );

  @override
  String crateApiMcpApiDefaultMcpVersion() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 36)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMcpApiDefaultMcpVersionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMcpApiDefaultMcpVersionConstMeta =>
      const TaskConstMeta(debugName: "default_mcp_version", argNames: []);

  @override
  String crateApiMcpApiExportMcpServersUiJson({
    required String serversJson,
    required bool isDesktop,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(serversJson, serializer);
          sse_encode_bool(isDesktop, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 37)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMcpApiExportMcpServersUiJsonConstMeta,
        argValues: [serversJson, isDesktop],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMcpApiExportMcpServersUiJsonConstMeta =>
      const TaskConstMeta(
        debugName: "export_mcp_servers_ui_json",
        argNames: ["serversJson", "isDesktop"],
      );

  @override
  String crateApiMcpApiGetMcpMethodNames() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 38)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMcpApiGetMcpMethodNamesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMcpApiGetMcpMethodNamesConstMeta =>
      const TaskConstMeta(debugName: "get_mcp_method_names", argNames: []);

  @override
  Future<void> crateApiModalProviderApiInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 39,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiModalProviderApiInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModalProviderApiInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  bool crateApiMcpApiIsMcpVersionSupported({required String version}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(version, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 40)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMcpApiIsMcpVersionSupportedConstMeta,
        argValues: [version],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMcpApiIsMcpVersionSupportedConstMeta =>
      const TaskConstMeta(
        debugName: "is_mcp_version_supported",
        argNames: ["version"],
      );

  @override
  String crateApiMcpApiJsonRpcErrorDetails({required int code}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_32(code, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 41)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMcpApiJsonRpcErrorDetailsConstMeta,
        argValues: [code],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMcpApiJsonRpcErrorDetailsConstMeta =>
      const TaskConstMeta(
        debugName: "json_rpc_error_details",
        argNames: ["code"],
      );

  @override
  String crateApiMcpApiLogLevelName({required String level}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(level, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 42)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMcpApiLogLevelNameConstMeta,
        argValues: [level],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMcpApiLogLevelNameConstMeta =>
      const TaskConstMeta(debugName: "log_level_name", argNames: ["level"]);

  @override
  String crateApiMcpClientApiMcpBuildTransportConfig({
    required String url,
    String? headersJson,
    required String transport,
    required BigInt timeoutMs,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          sse_encode_opt_String(headersJson, serializer);
          sse_encode_String(transport, serializer);
          sse_encode_u_64(timeoutMs, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 43)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMcpClientApiMcpBuildTransportConfigConstMeta,
        argValues: [url, headersJson, transport, timeoutMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMcpClientApiMcpBuildTransportConfigConstMeta =>
      const TaskConstMeta(
        debugName: "mcp_build_transport_config",
        argNames: ["url", "headersJson", "transport", "timeoutMs"],
      );

  @override
  String crateApiMcpClientApiMcpCallTool({
    required String url,
    String? headersJson,
    required String transport,
    required String toolName,
    String? argsJson,
    required BigInt timeoutMs,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          sse_encode_opt_String(headersJson, serializer);
          sse_encode_String(transport, serializer);
          sse_encode_String(toolName, serializer);
          sse_encode_opt_String(argsJson, serializer);
          sse_encode_u_64(timeoutMs, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 44)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMcpClientApiMcpCallToolConstMeta,
        argValues: [url, headersJson, transport, toolName, argsJson, timeoutMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMcpClientApiMcpCallToolConstMeta =>
      const TaskConstMeta(
        debugName: "mcp_call_tool",
        argNames: [
          "url",
          "headersJson",
          "transport",
          "toolName",
          "argsJson",
          "timeoutMs",
        ],
      );

  @override
  String crateApiMcpClientApiMcpConnect({
    required String url,
    String? headersJson,
    required String transport,
    required BigInt timeoutMs,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          sse_encode_opt_String(headersJson, serializer);
          sse_encode_String(transport, serializer);
          sse_encode_u_64(timeoutMs, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 45)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMcpClientApiMcpConnectConstMeta,
        argValues: [url, headersJson, transport, timeoutMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMcpClientApiMcpConnectConstMeta =>
      const TaskConstMeta(
        debugName: "mcp_connect",
        argNames: ["url", "headersJson", "transport", "timeoutMs"],
      );

  @override
  String crateApiMcpClientApiMcpListPrompts({
    required String url,
    String? headersJson,
    required String transport,
    required BigInt timeoutMs,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          sse_encode_opt_String(headersJson, serializer);
          sse_encode_String(transport, serializer);
          sse_encode_u_64(timeoutMs, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 46)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMcpClientApiMcpListPromptsConstMeta,
        argValues: [url, headersJson, transport, timeoutMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMcpClientApiMcpListPromptsConstMeta =>
      const TaskConstMeta(
        debugName: "mcp_list_prompts",
        argNames: ["url", "headersJson", "transport", "timeoutMs"],
      );

  @override
  String crateApiMcpClientApiMcpListResources({
    required String url,
    String? headersJson,
    required String transport,
    required BigInt timeoutMs,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          sse_encode_opt_String(headersJson, serializer);
          sse_encode_String(transport, serializer);
          sse_encode_u_64(timeoutMs, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 47)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMcpClientApiMcpListResourcesConstMeta,
        argValues: [url, headersJson, transport, timeoutMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMcpClientApiMcpListResourcesConstMeta =>
      const TaskConstMeta(
        debugName: "mcp_list_resources",
        argNames: ["url", "headersJson", "transport", "timeoutMs"],
      );

  @override
  String crateApiMcpClientApiMcpListTools({
    required String url,
    String? headersJson,
    required String transport,
    required BigInt timeoutMs,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          sse_encode_opt_String(headersJson, serializer);
          sse_encode_String(transport, serializer);
          sse_encode_u_64(timeoutMs, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 48)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMcpClientApiMcpListToolsConstMeta,
        argValues: [url, headersJson, transport, timeoutMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMcpClientApiMcpListToolsConstMeta =>
      const TaskConstMeta(
        debugName: "mcp_list_tools",
        argNames: ["url", "headersJson", "transport", "timeoutMs"],
      );

  @override
  Future<String> crateApiModalProviderApiModalProviderClassifyProviderKind({
    required String providerId,
    String? explicitType,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(providerId, serializer);
          sse_encode_opt_String(explicitType, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 49,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiModalProviderApiModalProviderClassifyProviderKindConstMeta,
        argValues: [providerId, explicitType],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiModalProviderApiModalProviderClassifyProviderKindConstMeta =>
      const TaskConstMeta(
        debugName: "modal_provider_classify_provider_kind",
        argNames: ["providerId", "explicitType"],
      );

  @override
  Future<String> crateApiModalProviderApiModalProviderCreateDefaultConfig({
    required String providerId,
    String? displayName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(providerId, serializer);
          sse_encode_opt_String(displayName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 50,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta:
            kCrateApiModalProviderApiModalProviderCreateDefaultConfigConstMeta,
        argValues: [providerId, displayName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiModalProviderApiModalProviderCreateDefaultConfigConstMeta =>
      const TaskConstMeta(
        debugName: "modal_provider_create_default_config",
        argNames: ["providerId", "displayName"],
      );

  @override
  Future<String> crateApiModalProviderApiModalProviderDefaultBaseUrl({
    required String providerId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(providerId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 51,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiModalProviderApiModalProviderDefaultBaseUrlConstMeta,
        argValues: [providerId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiModalProviderApiModalProviderDefaultBaseUrlConstMeta =>
      const TaskConstMeta(
        debugName: "modal_provider_default_base_url",
        argNames: ["providerId"],
      );

  @override
  Future<String>
  crateApiModalProviderApiModalProviderGetProviderDefaultHeaders({
    required String configJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(configJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 52,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta:
            kCrateApiModalProviderApiModalProviderGetProviderDefaultHeadersConstMeta,
        argValues: [configJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiModalProviderApiModalProviderGetProviderDefaultHeadersConstMeta =>
      const TaskConstMeta(
        debugName: "modal_provider_get_provider_default_headers",
        argNames: ["configJson"],
      );

  @override
  Future<String> crateApiModalProviderApiModalProviderListModels({
    required String configJson,
    String? siliconflowFallbackKey,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(configJson, serializer);
          sse_encode_opt_String(siliconflowFallbackKey, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 53,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiModalProviderApiModalProviderListModelsConstMeta,
        argValues: [configJson, siliconflowFallbackKey],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModalProviderApiModalProviderListModelsConstMeta =>
      const TaskConstMeta(
        debugName: "modal_provider_list_models",
        argNames: ["configJson", "siliconflowFallbackKey"],
      );

  @override
  Future<String> crateApiModalProviderApiModalProviderResolveApiModelId({
    required String configJson,
    required String modelId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(configJson, serializer);
          sse_encode_String(modelId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 54,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta:
            kCrateApiModalProviderApiModalProviderResolveApiModelIdConstMeta,
        argValues: [configJson, modelId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiModalProviderApiModalProviderResolveApiModelIdConstMeta =>
      const TaskConstMeta(
        debugName: "modal_provider_resolve_api_model_id",
        argNames: ["configJson", "modelId"],
      );

  @override
  Future<void> crateApiModalProviderApiModalProviderTestConnection({
    required String configJson,
    required String modelId,
    required bool useStream,
    String? siliconflowFallbackKey,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(configJson, serializer);
          sse_encode_String(modelId, serializer);
          sse_encode_bool(useStream, serializer);
          sse_encode_opt_String(siliconflowFallbackKey, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 55,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta:
            kCrateApiModalProviderApiModalProviderTestConnectionConstMeta,
        argValues: [configJson, modelId, useStream, siliconflowFallbackKey],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiModalProviderApiModalProviderTestConnectionConstMeta =>
      const TaskConstMeta(
        debugName: "modal_provider_test_connection",
        argNames: [
          "configJson",
          "modelId",
          "useStream",
          "siliconflowFallbackKey",
        ],
      );

  @override
  Future<void> crateApiModalProviderApiModalProviderValidateProviderConfig({
    required String configJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(configJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 56,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta:
            kCrateApiModalProviderApiModalProviderValidateProviderConfigConstMeta,
        argValues: [configJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiModalProviderApiModalProviderValidateProviderConfigConstMeta =>
      const TaskConstMeta(
        debugName: "modal_provider_validate_provider_config",
        argNames: ["configJson"],
      );

  @override
  String? crateApiMcpApiNegotiateMcpVersion({
    required List<String> clientVersions,
    required List<String> serverVersions,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_String(clientVersions, serializer);
          sse_encode_list_String(serverVersions, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 57)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMcpApiNegotiateMcpVersionConstMeta,
        argValues: [clientVersions, serverVersions],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMcpApiNegotiateMcpVersionConstMeta =>
      const TaskConstMeta(
        debugName: "negotiate_mcp_version",
        argNames: ["clientVersions", "serverVersions"],
      );

  @override
  String crateApiMcpApiNormalizeToolArguments({
    String? schemaJson,
    required String argsJson,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(schemaJson, serializer);
          sse_encode_String(argsJson, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 58)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMcpApiNormalizeToolArgumentsConstMeta,
        argValues: [schemaJson, argsJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMcpApiNormalizeToolArgumentsConstMeta =>
      const TaskConstMeta(
        debugName: "normalize_tool_arguments",
        argNames: ["schemaJson", "argsJson"],
      );

  @override
  String crateApiMcpApiParseMcpImportJson({
    required String rawJson,
    required bool isDesktop,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(rawJson, serializer);
          sse_encode_bool(isDesktop, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 59)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMcpApiParseMcpImportJsonConstMeta,
        argValues: [rawJson, isDesktop],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMcpApiParseMcpImportJsonConstMeta =>
      const TaskConstMeta(
        debugName: "parse_mcp_import_json",
        argNames: ["rawJson", "isDesktop"],
      );

  @override
  String crateApiAgentLoopApiRunClaudeAgentLoop({
    required String baseUrl,
    required String apiKey,
    required String modelId,
    required String messagesJson,
    String? systemPrompt,
    String? toolsJson,
    required bool stream,
    required bool isReasoning,
    int? thinkingBudget,
    double? temperature,
    int? maxTokens,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(baseUrl, serializer);
          sse_encode_String(apiKey, serializer);
          sse_encode_String(modelId, serializer);
          sse_encode_String(messagesJson, serializer);
          sse_encode_opt_String(systemPrompt, serializer);
          sse_encode_opt_String(toolsJson, serializer);
          sse_encode_bool(stream, serializer);
          sse_encode_bool(isReasoning, serializer);
          sse_encode_opt_box_autoadd_i_32(thinkingBudget, serializer);
          sse_encode_opt_box_autoadd_f_64(temperature, serializer);
          sse_encode_opt_box_autoadd_i_32(maxTokens, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 60)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAgentLoopApiRunClaudeAgentLoopConstMeta,
        argValues: [
          baseUrl,
          apiKey,
          modelId,
          messagesJson,
          systemPrompt,
          toolsJson,
          stream,
          isReasoning,
          thinkingBudget,
          temperature,
          maxTokens,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAgentLoopApiRunClaudeAgentLoopConstMeta =>
      const TaskConstMeta(
        debugName: "run_claude_agent_loop",
        argNames: [
          "baseUrl",
          "apiKey",
          "modelId",
          "messagesJson",
          "systemPrompt",
          "toolsJson",
          "stream",
          "isReasoning",
          "thinkingBudget",
          "temperature",
          "maxTokens",
        ],
      );

  @override
  String crateApiAgentLoopApiRunOpenaiAgentLoop({
    required String baseUrl,
    required String apiKey,
    required String modelId,
    required String messagesJson,
    String? toolsJson,
    required bool stream,
    required bool isReasoning,
    int? thinkingBudget,
    double? temperature,
    int? maxTokens,
    required bool useResponseApi,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(baseUrl, serializer);
          sse_encode_String(apiKey, serializer);
          sse_encode_String(modelId, serializer);
          sse_encode_String(messagesJson, serializer);
          sse_encode_opt_String(toolsJson, serializer);
          sse_encode_bool(stream, serializer);
          sse_encode_bool(isReasoning, serializer);
          sse_encode_opt_box_autoadd_i_32(thinkingBudget, serializer);
          sse_encode_opt_box_autoadd_f_64(temperature, serializer);
          sse_encode_opt_box_autoadd_i_32(maxTokens, serializer);
          sse_encode_bool(useResponseApi, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 61)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAgentLoopApiRunOpenaiAgentLoopConstMeta,
        argValues: [
          baseUrl,
          apiKey,
          modelId,
          messagesJson,
          toolsJson,
          stream,
          isReasoning,
          thinkingBudget,
          temperature,
          maxTokens,
          useResponseApi,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAgentLoopApiRunOpenaiAgentLoopConstMeta =>
      const TaskConstMeta(
        debugName: "run_openai_agent_loop",
        argNames: [
          "baseUrl",
          "apiKey",
          "modelId",
          "messagesJson",
          "toolsJson",
          "stream",
          "isReasoning",
          "thinkingBudget",
          "temperature",
          "maxTokens",
          "useResponseApi",
        ],
      );

  @override
  Future<String> crateApiMcpApiSummarizeServerTools({
    required String toolsJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(toolsJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 62,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMcpApiSummarizeServerToolsConstMeta,
        argValues: [toolsJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMcpApiSummarizeServerToolsConstMeta =>
      const TaskConstMeta(
        debugName: "summarize_server_tools",
        argNames: ["toolsJson"],
      );

  @override
  List<String> crateApiMcpApiSupportedMcpVersions() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 63)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMcpApiSupportedMcpVersionsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMcpApiSupportedMcpVersionsConstMeta =>
      const TaskConstMeta(debugName: "supported_mcp_versions", argNames: []);

  @override
  Future<void> crateApiMcpApiValidateMcpServerConfig({
    required String configJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(configJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 64,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMcpApiValidateMcpServerConfigConstMeta,
        argValues: [configJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMcpApiValidateMcpServerConfigConstMeta =>
      const TaskConstMeta(
        debugName: "validate_mcp_server_config",
        argNames: ["configJson"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_64(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_32(raw);
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_64(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_32(deserializer));
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_32(self, serializer);
    }
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
