// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/provider_api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiProviderApiInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -1410334620;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'model_provider_rust',
        ioDirectory: 'rust-lib/model-provider-rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateApiProviderApiClassifyProviderKind({
    required String providerId,
    String? explicitType,
  });

  Future<String> crateApiProviderApiCreateDefaultConfig({
    required String providerId,
    String? displayName,
  });

  Future<String> crateApiProviderApiDefaultBaseUrl({
    required String providerId,
  });

  Future<String> crateApiProviderApiGetProviderDefaultHeaders({
    required String configJson,
  });

  Future<void> crateApiProviderApiInitApp();

  Future<String> crateApiProviderApiListModels({
    required String configJson,
    String? siliconflowFallbackKey,
  });

  Future<String> crateApiProviderApiResolveApiModelId({
    required String configJson,
    required String modelId,
  });

  Future<void> crateApiProviderApiTestConnection({
    required String configJson,
    required String modelId,
    required bool useStream,
    String? siliconflowFallbackKey,
  });

  Future<void> crateApiProviderApiValidateProviderConfig({
    required String configJson,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiProviderApiClassifyProviderKind({
    required String providerId,
    String? explicitType,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(providerId, serializer);
          sse_encode_opt_String(explicitType, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProviderApiClassifyProviderKindConstMeta,
        argValues: [providerId, explicitType],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProviderApiClassifyProviderKindConstMeta =>
      const TaskConstMeta(
        debugName: "classify_provider_kind",
        argNames: ["providerId", "explicitType"],
      );

  @override
  Future<String> crateApiProviderApiCreateDefaultConfig({
    required String providerId,
    String? displayName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(providerId, serializer);
          sse_encode_opt_String(displayName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiProviderApiCreateDefaultConfigConstMeta,
        argValues: [providerId, displayName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProviderApiCreateDefaultConfigConstMeta =>
      const TaskConstMeta(
        debugName: "create_default_config",
        argNames: ["providerId", "displayName"],
      );

  @override
  Future<String> crateApiProviderApiDefaultBaseUrl({
    required String providerId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(providerId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProviderApiDefaultBaseUrlConstMeta,
        argValues: [providerId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProviderApiDefaultBaseUrlConstMeta =>
      const TaskConstMeta(
        debugName: "default_base_url",
        argNames: ["providerId"],
      );

  @override
  Future<String> crateApiProviderApiGetProviderDefaultHeaders({
    required String configJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(configJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiProviderApiGetProviderDefaultHeadersConstMeta,
        argValues: [configJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProviderApiGetProviderDefaultHeadersConstMeta =>
      const TaskConstMeta(
        debugName: "get_provider_default_headers",
        argNames: ["configJson"],
      );

  @override
  Future<void> crateApiProviderApiInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProviderApiInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProviderApiInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<String> crateApiProviderApiListModels({
    required String configJson,
    String? siliconflowFallbackKey,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(configJson, serializer);
          sse_encode_opt_String(siliconflowFallbackKey, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiProviderApiListModelsConstMeta,
        argValues: [configJson, siliconflowFallbackKey],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProviderApiListModelsConstMeta =>
      const TaskConstMeta(
        debugName: "list_models",
        argNames: ["configJson", "siliconflowFallbackKey"],
      );

  @override
  Future<String> crateApiProviderApiResolveApiModelId({
    required String configJson,
    required String modelId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(configJson, serializer);
          sse_encode_String(modelId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiProviderApiResolveApiModelIdConstMeta,
        argValues: [configJson, modelId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProviderApiResolveApiModelIdConstMeta =>
      const TaskConstMeta(
        debugName: "resolve_api_model_id",
        argNames: ["configJson", "modelId"],
      );

  @override
  Future<void> crateApiProviderApiTestConnection({
    required String configJson,
    required String modelId,
    required bool useStream,
    String? siliconflowFallbackKey,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(configJson, serializer);
          sse_encode_String(modelId, serializer);
          sse_encode_bool(useStream, serializer);
          sse_encode_opt_String(siliconflowFallbackKey, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiProviderApiTestConnectionConstMeta,
        argValues: [configJson, modelId, useStream, siliconflowFallbackKey],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProviderApiTestConnectionConstMeta =>
      const TaskConstMeta(
        debugName: "test_connection",
        argNames: [
          "configJson",
          "modelId",
          "useStream",
          "siliconflowFallbackKey",
        ],
      );

  @override
  Future<void> crateApiProviderApiValidateProviderConfig({
    required String configJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(configJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiProviderApiValidateProviderConfigConstMeta,
        argValues: [configJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProviderApiValidateProviderConfigConstMeta =>
      const TaskConstMeta(
        debugName: "validate_provider_config",
        argNames: ["configJson"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
