// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Run the OpenAI-compatible agent loop.
///
/// Executes the full agent cycle: send request → parse SSE → yield events →
/// execute tool calls → loop until done.
///
/// Returns a JSON string of the final accumulated content.
///
/// # Arguments
/// * `config_json` - Provider config JSON
/// * `messages_json` - Messages array JSON
/// * `tools_json` - Optional tool definitions JSON
/// * `stream` - Whether to use SSE streaming
/// * `is_reasoning` - Whether model supports reasoning
/// * `thinking_budget` - Reasoning token budget
/// * `temperature` - Sampling temperature
/// * `max_tokens` - Max completion tokens
/// * `use_response_api` - Use OpenAI Responses API
/// * `on_event_json` - Callback that receives AgentEvent JSON
String runOpenaiAgentLoop({
  required String baseUrl,
  required String apiKey,
  required String modelId,
  required String messagesJson,
  String? toolsJson,
  required bool stream,
  required bool isReasoning,
  int? thinkingBudget,
  double? temperature,
  int? maxTokens,
  required bool useResponseApi,
}) => RustLib.instance.api.crateApiAgentLoopApiRunOpenaiAgentLoop(
  baseUrl: baseUrl,
  apiKey: apiKey,
  modelId: modelId,
  messagesJson: messagesJson,
  toolsJson: toolsJson,
  stream: stream,
  isReasoning: isReasoning,
  thinkingBudget: thinkingBudget,
  temperature: temperature,
  maxTokens: maxTokens,
  useResponseApi: useResponseApi,
);

/// Run the Claude agent loop.
///
/// Executes the full agent cycle for Claude API: send request → parse SSE → yield events →
/// execute tool calls → loop until done.
///
/// Returns a JSON string of the final accumulated content.
String runClaudeAgentLoop({
  required String baseUrl,
  required String apiKey,
  required String modelId,
  required String messagesJson,
  String? systemPrompt,
  String? toolsJson,
  required bool stream,
  required bool isReasoning,
  int? thinkingBudget,
  double? temperature,
  int? maxTokens,
}) => RustLib.instance.api.crateApiAgentLoopApiRunClaudeAgentLoop(
  baseUrl: baseUrl,
  apiKey: apiKey,
  modelId: modelId,
  messagesJson: messagesJson,
  systemPrompt: systemPrompt,
  toolsJson: toolsJson,
  stream: stream,
  isReasoning: isReasoning,
  thinkingBudget: thinkingBudget,
  temperature: temperature,
  maxTokens: maxTokens,
);
