// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AgentLoopResult`, `AgentLoopState`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// Start the OpenAI-compatible agent loop. Returns first round result.
Future<String> startOpenaiAgentLoop({
  required String baseUrl,
  required String apiKey,
  required String modelId,
  required String messagesJson,
  String? toolsJson,
  required bool stream,
  required bool isReasoning,
  int? thinkingBudget,
  double? temperature,
  int? maxTokens,
  required bool useResponseApi,
}) => RustLib.instance.api.crateApiAgentLoopApiStartOpenaiAgentLoop(
  baseUrl: baseUrl,
  apiKey: apiKey,
  modelId: modelId,
  messagesJson: messagesJson,
  toolsJson: toolsJson,
  stream: stream,
  isReasoning: isReasoning,
  thinkingBudget: thinkingBudget,
  temperature: temperature,
  maxTokens: maxTokens,
  useResponseApi: useResponseApi,
);

/// Continue the agent loop after tool execution.
/// Receives tool results and runs the next round.
Future<String> continueOpenaiAgentLoop({
  required String stateJson,
  required String toolResultsJson,
}) => RustLib.instance.api.crateApiAgentLoopApiContinueOpenaiAgentLoop(
  stateJson: stateJson,
  toolResultsJson: toolResultsJson,
);

/// Start the Claude agent loop. Returns first round result.
Future<String> startClaudeAgentLoop({
  required String baseUrl,
  required String apiKey,
  required String modelId,
  required String messagesJson,
  String? systemPrompt,
  String? toolsJson,
  required bool stream,
  required bool isReasoning,
  int? thinkingBudget,
  double? temperature,
  int? maxTokens,
}) => RustLib.instance.api.crateApiAgentLoopApiStartClaudeAgentLoop(
  baseUrl: baseUrl,
  apiKey: apiKey,
  modelId: modelId,
  messagesJson: messagesJson,
  systemPrompt: systemPrompt,
  toolsJson: toolsJson,
  stream: stream,
  isReasoning: isReasoning,
  thinkingBudget: thinkingBudget,
  temperature: temperature,
  maxTokens: maxTokens,
);

/// Continue the Claude agent loop after tool execution.
Future<String> continueClaudeAgentLoop({
  required String stateJson,
  required String toolResultsJson,
}) => RustLib.instance.api.crateApiAgentLoopApiContinueClaudeAgentLoop(
  stateJson: stateJson,
  toolResultsJson: toolResultsJson,
);
