// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_config`, `parse_headers`

/// Initialize MCP connection and return server info + tools list in one call.
String mcpConnect({
  required String url,
  String? headersJson,
  required String transport,
  required BigInt timeoutMs,
}) => RustLib.instance.api.crateApiMcpClientApiMcpConnect(
  url: url,
  headersJson: headersJson,
  transport: transport,
  timeoutMs: timeoutMs,
);

/// List tools from an MCP server.
String mcpListTools({
  required String url,
  String? headersJson,
  required String transport,
  required BigInt timeoutMs,
}) => RustLib.instance.api.crateApiMcpClientApiMcpListTools(
  url: url,
  headersJson: headersJson,
  transport: transport,
  timeoutMs: timeoutMs,
);

/// Call a tool on an MCP server.
String mcpCallTool({
  required String url,
  String? headersJson,
  required String transport,
  required String toolName,
  String? argsJson,
  required BigInt timeoutMs,
}) => RustLib.instance.api.crateApiMcpClientApiMcpCallTool(
  url: url,
  headersJson: headersJson,
  transport: transport,
  toolName: toolName,
  argsJson: argsJson,
  timeoutMs: timeoutMs,
);

/// List resources from an MCP server.
String mcpListResources({
  required String url,
  String? headersJson,
  required String transport,
  required BigInt timeoutMs,
}) => RustLib.instance.api.crateApiMcpClientApiMcpListResources(
  url: url,
  headersJson: headersJson,
  transport: transport,
  timeoutMs: timeoutMs,
);

/// List prompts from an MCP server.
String mcpListPrompts({
  required String url,
  String? headersJson,
  required String transport,
  required BigInt timeoutMs,
}) => RustLib.instance.api.crateApiMcpClientApiMcpListPrompts(
  url: url,
  headersJson: headersJson,
  transport: transport,
  timeoutMs: timeoutMs,
);

/// Build MCP transport config JSON (for Dart to use when calling other MCP functions).
String mcpBuildTransportConfig({
  required String url,
  String? headersJson,
  required String transport,
  required BigInt timeoutMs,
}) => RustLib.instance.api.crateApiMcpClientApiMcpBuildTransportConfig(
  url: url,
  headersJson: headersJson,
  transport: transport,
  timeoutMs: timeoutMs,
);
