// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

List<String> supportedMcpVersions() =>
    RustLib.instance.api.crateApiMcpApiSupportedMcpVersions();

String defaultMcpVersion() =>
    RustLib.instance.api.crateApiMcpApiDefaultMcpVersion();

String? negotiateMcpVersion({
  required List<String> clientVersions,
  required List<String> serverVersions,
}) => RustLib.instance.api.crateApiMcpApiNegotiateMcpVersion(
  clientVersions: clientVersions,
  serverVersions: serverVersions,
);

bool isMcpVersionSupported({required String version}) =>
    RustLib.instance.api.crateApiMcpApiIsMcpVersionSupported(version: version);

Future<String> buildJsonRpcRequest({
  required String idJson,
  required String method,
  String? paramsJson,
}) => RustLib.instance.api.crateApiMcpApiBuildJsonRpcRequest(
  idJson: idJson,
  method: method,
  paramsJson: paramsJson,
);

Future<String> buildJsonRpcNotification({
  required String method,
  String? paramsJson,
}) => RustLib.instance.api.crateApiMcpApiBuildJsonRpcNotification(
  method: method,
  paramsJson: paramsJson,
);

Future<String> buildInitializeRequest({
  required String clientName,
  required String clientVersion,
  String? protocolVersion,
}) => RustLib.instance.api.crateApiMcpApiBuildInitializeRequest(
  clientName: clientName,
  clientVersion: clientVersion,
  protocolVersion: protocolVersion,
);

Future<String> buildListToolsRequest({required String idJson}) =>
    RustLib.instance.api.crateApiMcpApiBuildListToolsRequest(idJson: idJson);

Future<String> buildCallToolRequest({
  required String idJson,
  required String toolName,
  String? argsJson,
}) => RustLib.instance.api.crateApiMcpApiBuildCallToolRequest(
  idJson: idJson,
  toolName: toolName,
  argsJson: argsJson,
);

Future<String> buildListResourcesRequest({required String idJson}) => RustLib
    .instance
    .api
    .crateApiMcpApiBuildListResourcesRequest(idJson: idJson);

Future<String> buildReadResourceRequest({
  required String idJson,
  required String uri,
}) => RustLib.instance.api.crateApiMcpApiBuildReadResourceRequest(
  idJson: idJson,
  uri: uri,
);

Future<String> buildListPromptsRequest({required String idJson}) =>
    RustLib.instance.api.crateApiMcpApiBuildListPromptsRequest(idJson: idJson);

Future<String> buildGetPromptRequest({
  required String idJson,
  required String promptName,
  String? argsJson,
}) => RustLib.instance.api.crateApiMcpApiBuildGetPromptRequest(
  idJson: idJson,
  promptName: promptName,
  argsJson: argsJson,
);

Future<String> buildHealthCheckRequest({required String idJson}) =>
    RustLib.instance.api.crateApiMcpApiBuildHealthCheckRequest(idJson: idJson);

Future<void> validateMcpServerConfig({required String configJson}) => RustLib
    .instance
    .api
    .crateApiMcpApiValidateMcpServerConfig(configJson: configJson);

Future<String> createDefaultMcpConfig({
  required String name,
  required String transport,
  required String url,
}) => RustLib.instance.api.crateApiMcpApiCreateDefaultMcpConfig(
  name: name,
  transport: transport,
  url: url,
);

Future<String> summarizeServerTools({required String toolsJson}) => RustLib
    .instance
    .api
    .crateApiMcpApiSummarizeServerTools(toolsJson: toolsJson);

String exportMcpServersUiJson({
  required String serversJson,
  required bool isDesktop,
}) => RustLib.instance.api.crateApiMcpApiExportMcpServersUiJson(
  serversJson: serversJson,
  isDesktop: isDesktop,
);

String parseMcpImportJson({required String rawJson, required bool isDesktop}) =>
    RustLib.instance.api.crateApiMcpApiParseMcpImportJson(
      rawJson: rawJson,
      isDesktop: isDesktop,
    );

String normalizeToolArguments({String? schemaJson, required String argsJson}) =>
    RustLib.instance.api.crateApiMcpApiNormalizeToolArguments(
      schemaJson: schemaJson,
      argsJson: argsJson,
    );

String getMcpMethodNames() =>
    RustLib.instance.api.crateApiMcpApiGetMcpMethodNames();

String jsonRpcErrorDetails({required int code}) =>
    RustLib.instance.api.crateApiMcpApiJsonRpcErrorDetails(code: code);

String logLevelName({required String level}) =>
    RustLib.instance.api.crateApiMcpApiLogLevelName(level: level);
