// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<String> modalProviderResolveApiModelId({
  required String configJson,
  required String modelId,
}) =>
    RustLib.instance.api.crateApiModalProviderApiModalProviderResolveApiModelId(
      configJson: configJson,
      modelId: modelId,
    );

Future<String> modalProviderClassifyProviderKind({
  required String providerId,
  String? explicitType,
}) => RustLib.instance.api
    .crateApiModalProviderApiModalProviderClassifyProviderKind(
      providerId: providerId,
      explicitType: explicitType,
    );

Future<String> modalProviderDefaultBaseUrl({required String providerId}) =>
    RustLib.instance.api.crateApiModalProviderApiModalProviderDefaultBaseUrl(
      providerId: providerId,
    );

Future<String> modalProviderGetProviderDefaultHeaders({
  required String configJson,
}) => RustLib.instance.api
    .crateApiModalProviderApiModalProviderGetProviderDefaultHeaders(
      configJson: configJson,
    );

Future<String> modalProviderListModels({
  required String configJson,
  String? siliconflowFallbackKey,
}) => RustLib.instance.api.crateApiModalProviderApiModalProviderListModels(
  configJson: configJson,
  siliconflowFallbackKey: siliconflowFallbackKey,
);

Future<void> modalProviderTestConnection({
  required String configJson,
  required String modelId,
  required bool useStream,
  String? siliconflowFallbackKey,
}) => RustLib.instance.api.crateApiModalProviderApiModalProviderTestConnection(
  configJson: configJson,
  modelId: modelId,
  useStream: useStream,
  siliconflowFallbackKey: siliconflowFallbackKey,
);

Future<void> modalProviderValidateProviderConfig({
  required String configJson,
}) => RustLib.instance.api
    .crateApiModalProviderApiModalProviderValidateProviderConfig(
      configJson: configJson,
    );

Future<String> modalProviderCreateDefaultConfig({
  required String providerId,
  String? displayName,
}) => RustLib.instance.api
    .crateApiModalProviderApiModalProviderCreateDefaultConfig(
      providerId: providerId,
      displayName: displayName,
    );
