// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `default_base_url_for`, `default_provider_headers`, `is_siliconflow_host`, `regex_find`, `resolve_api_model_id_from_config`, `url_host`

/// 从配置中的 modelOverrides 解析上游模型 ID（apiModelId）。
/// 如果 modelOverrides 里没有为 model_id 指定 apiModelId，则返回原 model_id。
Future<String> resolveApiModelId({
  required String configJson,
  required String modelId,
}) => RustLib.instance.api.crateApiProviderApiResolveApiModelId(
  configJson: configJson,
  modelId: modelId,
);

/// 根据 provider id 和显式类型分类供应商类型。
/// 返回 JSON 格式的 ProviderKind 枚举值（"openai" | "claude"）。
Future<String> classifyProviderKind({
  required String providerId,
  String? explicitType,
}) => RustLib.instance.api.crateApiProviderApiClassifyProviderKind(
  providerId: providerId,
  explicitType: explicitType,
);

/// 获取已知供应商的默认 Base URL（仅基于 provider id 名推断）。
/// 这部分是硬编码的预设值，和 Kelivo 原实现一致。
Future<String> defaultBaseUrl({required String providerId}) => RustLib
    .instance
    .api
    .crateApiProviderApiDefaultBaseUrl(providerId: providerId);

/// 获取供应商的默认 HTTP 请求头（如 OpenRouter 的标识头）。
/// 返回 JSON map。
Future<String> getProviderDefaultHeaders({required String configJson}) =>
    RustLib.instance.api.crateApiProviderApiGetProviderDefaultHeaders(
      configJson: configJson,
    );

/// 从 API 获取模型列表。
/// 向 `{baseUrl}/models` 发送 GET 请求，解析并推断每个模型的能力标签。
/// 返回 JSON 数组的 ModelInfo。
///
/// SiliconFlow 无 key 时限制为 2 个免费模型（硬编码白名单，与 Kelivo 一致）。
Future<String> listModels({
  required String configJson,
  String? siliconflowFallbackKey,
}) => RustLib.instance.api.crateApiProviderApiListModels(
  configJson: configJson,
  siliconflowFallbackKey: siliconflowFallbackKey,
);

/// 测试供应商连接。
/// 向对应 API 端点发送最小聊天请求，验证凭证和模型是否可达。
Future<void> testConnection({
  required String configJson,
  required String modelId,
  required bool useStream,
  String? siliconflowFallbackKey,
}) => RustLib.instance.api.crateApiProviderApiTestConnection(
  configJson: configJson,
  modelId: modelId,
  useStream: useStream,
  siliconflowFallbackKey: siliconflowFallbackKey,
);

/// 校验 ProviderConfig 配置合法性（无网络调用）。
/// 返回 Ok(()) 或错误信息字符串。
Future<void> validateProviderConfig({required String configJson}) => RustLib
    .instance
    .api
    .crateApiProviderApiValidateProviderConfig(configJson: configJson);

/// 为指定 provider id 创建默认 ProviderConfig（JSON 模板）。
/// 对齐 Kelivo 的 ProviderConfig.defaultsFor()。
/// 返回 JSON 格式的 ProviderConfig，供 Flutter 侧初始化供应商用。
Future<String> createDefaultConfig({
  required String providerId,
  String? displayName,
}) => RustLib.instance.api.crateApiProviderApiCreateDefaultConfig(
  providerId: providerId,
  displayName: displayName,
);
