// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'agent_loop.freezed.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ToolCallInfo>>
abstract class ToolCallInfo implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ToolResultInfo>>
abstract class ToolResultInfo implements RustOpaqueInterface {}

@freezed
sealed class AgentEvent with _$AgentEvent {
  const AgentEvent._();

  /// Text content delta from the model.
  const factory AgentEvent.content({required String text}) = AgentEvent_Content;

  /// Reasoning/thinking delta.
  const factory AgentEvent.reasoning({required String text}) =
      AgentEvent_Reasoning;

  /// Image output from the model.
  const factory AgentEvent.image({required String url}) = AgentEvent_Image;

  /// Tool calls requested by the model (batch).
  const factory AgentEvent.toolCalls({required List<ToolCallInfo> calls}) =
      AgentEvent_ToolCalls;

  /// Results after tool execution.
  const factory AgentEvent.toolResults({
    required List<ToolResultInfo> results,
  }) = AgentEvent_ToolResults;

  /// Token usage update.
  const factory AgentEvent.usage({
    required int promptTokens,
    required int completionTokens,
    required int totalTokens,
  }) = AgentEvent_Usage;

  /// Stream finished (no more tool calls).
  const factory AgentEvent.done() = AgentEvent_Done;

  /// Error occurred.
  const factory AgentEvent.error({required String message}) = AgentEvent_Error;
}
